version: '3.5'

services:

  db-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-db-master
    volumes:
      - ./db-data-master:/var/lib/postgresql/data
      - ./init-master.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./custom_master_pg_hba.conf:/etc/custom_pg_hba.conf:ro
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    command: [
      "-c", "hba_file=/etc/custom_pg_hba.conf",
      "-c", "wal_level=replica",
      "-c", "max_wal_senders=10",
      "-c", "wal_keep_size=1024"
    ]

  db-slave:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-db-slave
    volumes:
      - ./db-data-slave:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5433:5432
    command: [
      "-c", "hot_standby=on",
      "-c", "primary_conninfo=postgresql://rep_user:pass@db-master:5432"
    ]

volumes:
  db-data-master:
  db-data-slave:
